# Generated by Django 5.1.5 on 2025-03-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0002_review_rating_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movie_review.movie'),
        ),
    ]
