# Generated by Django 5.1.5 on 2025-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0008_review_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.IntegerField(default=0),
        ),
    ]
