# Generated by Django 5.1.5 on 2025-03-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0009_remove_review_sentiment_comment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
